### ISSUE TITLE
ATM Script/Interface Button Issue

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [Andyyy7666/Currency-System#6]
The Withdraw or sometimes Confirm button often times does not let anyone click it. In console it says could not focus. Is there a known fix for it on the client side? Thank you.

![image](https://user-images.githubusercontent.com/25211271/164259440-827417b2-7a46-4ae9-90a8-64244cbf893d.png)

**Comment by Andyyy7666** [comment]
This is fixed.
